Add startAfter argument to start scrolling after a duration
marcelgarus/marquee pull request #40
Opened 2020-08-29 14:31 UTC by hacker1024

As discussed in #39.

2020-08-31 19:19 UTC, marcelgarus requested changes

2020-08-31 19:19 UTC, marcelgarus commented on lib/marquee.dart
> +  /// This Marqee starts scrolling one second after being displayed.
```suggestion
  /// This [Marquee] starts scrolling one second after being displayed.
```

2020-08-31 19:20 UTC, marcelgarus commented
Apart from the typo, this looks really good to me. Looking forward to merging this! 😄
Also, thanks for taking the time to contribute and creating a PR, I really appreciate that.

2020-09-02 03:01 UTC, hacker1024 commented
Fixed.

> Also, thanks for taking the time to contribute and creating a PR, I really appreciate that.

No problem, it was surprisingly simple.

2020-09-02 08:47 UTC, merged

2020-09-02 08:49 UTC, marcelgarus commented
Nice, I published this as version 1.6.0 on pub.dev